config/routes.rb
Todos::Application.routes.draw do

  resources :tasks do
    member do
      put :fire
    end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index, :show, :destroy]

  resources :sessions, :except => [:index, :show]

  root "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user

  before_create :set_state

  scope :state_is, lambda { |st| where(:state => st) }

  def complete
    self.update_attributes(:state => "completed")
  end

  def delete
    self.update_attributes(:state => "deleted")
  end

  private

  def set_state
    self.state = 'new'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password #see bcrypt-ruby

  validates_uniqueness_of :email
  validates_length_of :password, :minimum => 6
  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :current_user
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to tasks_path and return if current_user.present?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end



  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize
  before_action :set_task, only: [:show, :edit, :update, :destroy, :fire]

  # GET /tasks
  # GET /tasks.json
  def index
    params[:s] ||= "new"
    @tasks = current_user.tasks.state_is(params[:s])
  end

  def fire
    @task.send(params[:e].to_sym) if @task.respond_to?(params[:e].to_sym)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = current_user.tasks.where(:id => params[:id]).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :state)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, :only => [:edit, :update]

  before_action :set_user, only: [:show, :edit, :update, :destroy]



  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'Your account successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="pagination-centered">

  <h1>Welcome to Todos application!</h1>
  <p>This application is developed as a freelancer.com project.</p>


  <div class="well">
    You need to <%= link_to "Login", login_url %> or <%= link_to "Signup", new_user_url %> to continue
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Todos" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<div id="wrap">
  <div class="navbar navbar-fluid-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="brand" href="<%= root_path %>">Todos</a>

        <div class="container-fluid ">
          <ul class="nav pull-right">
            <li>
              <% if @current_user.nil? %>
                  <%= link_to "Login <i class='icon-signin'></i>".html_safe, new_session_path %>
              <% else %>

                  <ul class="nav navbar-nav pull-right">
                    <li id="fat-menu" class="dropdown">
                      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= "Hi #{@current_user.email}" %> <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li>
                          <%= link_to "<i class='icon-user'></i> My Account".html_safe, edit_user_path(current_user) %>
                        </li>
                        <li>
                          <%= link_to "<i class='icon-signin'></i> Logout".html_safe, logout_url, :method => :delete %>
                        </li>
                      </ul>
                    </li>
                  </ul>


              <% end %>
            </li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12" id="main-content">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>
    <!--/row-->
  </div>
  <!-- /container -->
</div>
<!-- /wrap -->
<div id="footer">
  <div class="container">
    <p class="footer-content">&copy; Todos <%= Date.today.year %></p>
  </div>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/_task_list.html.erb
<% unless @tasks.blank? %>


    <table class="table table-striped">
      <thead>

      </thead>
      <tbody>
      <% @tasks.each do |task| %>
          <tr class="tasks" id="<%= task.id %>">
            <td><%= link_to task.name, task_path(task) %></td>
            <td><%= time_ago_in_words(task.created_at) %> ago</td>
            <td>
              <% if task.state != "completed" %>
                  <%= link_to 'Completed',
                              fire_task_path(task, :e => "complete", :dom_id => task.id),
                              :method => :put,
                              :remote => true,
                              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                              :class => 'btn btn-mini btn-info' %>

              <% else %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              fire_task_path(task, :e => "delete", :dom_id => task.id),
                              :method => 'put',
                              :remote => true,
                              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                              :class => 'btn btn-mini btn-danger' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <div class="well paginate-center">
      <i class="icon-info-sign"></i>
      No task found</p>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/fire.js.erb
$("#<%= params[:dom_id] %>").fadeOut();
$("#<%= params[:dom_id] %>").remove();

if($('.tasks').length == 0) {
    $('#task-list').html("<div class='well'><i class='icon-info-sign'></i> No task found </div>")
}

app/views/tasks/index.html.erb
<%- model_class = Task -%>

<%= form_for Task.new, :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.text_field :name, :class => 'input-xxlarge', :style => "width:99%;", :placeholder => "Enter new task and press enter" %>
<% end %>

<%= form_for tasks_path, :method => :get, :remote => true, :html => {:class => 'form-horizontal'} do |f| %>
    List: <%= select_tag "s", options_for_select({"New Tasks" => "new", "Completed Tasks" => "completed"}, params[:s]), :id => "task-state-select" %>
<% end %>


<div id="task-list">
  <%= render partial: "task_list" %>
</div>

<script>
    $('#task-state-select').on('change', function () {
        $(this).parent('form').submit();
    });
</script>

app/views/tasks/index.js.erb
$('#task-list').html("<%= escape_javascript(render :partial => 'task_list', :formats => [:html], :handlers => [:erb]) %>");

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @task.state %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn' %>                 |
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>              |
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>

    <% if @user.errors.any? %>
        <div class="well well-small" style="border: 1px solid red;">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.email_field :email, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit button_name, :class => 'btn btn-primary' %>
      <% if @user.new_record? %>
          or
          <%= link_to "Have an account?",
                      new_session_path, :class => 'btn' %>
      <% end %>
    </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= "My Account" %></h1>
</div>
<%= render :partial => 'form', :locals => {:button_name => "Update"} %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password_digest) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Sign Up</h1>
</div>
<%= render :partial => 'form', :locals => {:button_name => "Sign Up"} %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password_digest) %>:</strong></dt>
  <dd><%= @user.password_digest %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>